server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
spring:
  application:
    name: rpc-client

rpc:
  client:
      zk:
        root: /rpc
        addr: 192.168.0.37:2181
        switch: true
        timeout: 10000
      api:
        package: com.itcast.rpc.api
  cluster:
        strategy: random